[platformio]
default_envs = node_wc, gateway_router
src_dir = src
include_dir = include

[env]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

[env:node_wc]
build_flags = -D IS_NODE_WC
lib_deps =
    jgromes/RadioLib@^6.6.0
    teckel12/NewPing@^1.9.7

[env:gateway_router]
build_flags = -D IS_GATEWAY
lib_deps =
    jgromes/RadioLib@^6.6.0
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.4
