[platformio]
default_envs = node_wc
src_dir = .

[env:node_wc]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = 
    -<*>
    +<src/>
build_flags = 
    -D IS_NODE_WC
    -D CORE_DEBUG_LEVEL=3
    -I include
lib_deps =
    jgromes/RadioLib@^6.6.0
    teckel12/NewPing@^1.9.7
    madhephaestus/ESP32Servo@^3.0.5
    # DILARANG KERAS memasukkan WiFi.h atau PubSubClient di sini [ADR-02]

[env:test_mq_sensors]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = 
    -<*>
    +<standalone_test/test_mq_sensors/>
build_flags = 
    -D CORE_DEBUG_LEVEL=3

[env:test_jsn_sr04t]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = 
    -<*>
    +<standalone_test/test_jsn_sr04t/>
build_flags = 
    -D CORE_DEBUG_LEVEL=3
lib_deps = 
    teckel12/NewPing@^1.9.7



